In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr = np.array(my_list)

In [5]:
arr  # one dimensional array

array([1, 2, 3])

In [6]:
# two dimensional array, a list of lists

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
# cast to array to get 2D array, like a matrix

In [9]:
np.array(my_mat)  # two sets of brackets indicates it's a 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# most common way of creating a numpy array


In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(0,11,2)   # Jumps in steps of 2 --> np.arange(from, To, Step-size)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [16]:
np.zeros((5,5))  # using a Tuple, you can create a matrix: (# Rows, # of Coloumns)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [17]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [18]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [19]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [20]:
# arange returns integers out, from a (start, stop, and given step size)

# Linspace takes in a 3rd arguement of the number of points you want

In [21]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [22]:
np.linspace(0,5,100)

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

In [23]:
# np.eye creates an identity matrix

In [24]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [25]:
# ways to create arrays of random numbers

In [26]:
np.random.rand()  # creates an array of the given shape you pass in, 
                 # and populates it with random samples from uniform distribution

0.837589255095319

In [27]:
np.random.rand(5)

array([ 0.36369756,  0.60831044,  0.48453776,  0.73680234,  0.34392615])

In [28]:
np.random.randn(2)  # returns sample from normal distribution or gaussian

array([ 0.37618157, -0.64111335])

In [29]:
# np.random.randint(low,high, actual size you want)

np.random.randint(1,100,10)

array([ 9,  4, 63, 77, 76,  6, 17, 34, 65,  7])

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([17, 36, 12, 43,  1, 31, 27, 19, 19, 11])

In [34]:
# one of the most useful methods you can use on array; 
# Reshape Method - returns array containing the same data with a new shape

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
# get an error if you cant fill up the matrix

arr.reshape(5,10)   # need 50 elements to do this

ValueError: cannot reshape array of size 25 into shape (5,10)

In [37]:
ranarr

array([17, 36, 12, 43,  1, 31, 27, 19, 19, 11])

In [38]:
ranarr.max()

# returns the max value of your array

43

In [39]:
ranarr.min()

1

In [40]:
# to find the location of the max or min

In [41]:
ranarr.argmax()  # this tells us where our max value is located, i.e., 43 is located at index 3

3

In [42]:
ranarr.argmin()

4

In [43]:
arr.shape

(25,)

In [44]:
arr = arr.reshape(5,5)

In [45]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr.shape 

(5, 5)

In [47]:
# to find what data type you have in an array

arr.dtype

dtype('int64')

In [48]:
# to avoid typing in np.random.randint

In [49]:
from numpy.random import randint

In [50]:
randint(2,10)

5


********************************************************************************************************************************
Quick Note on Array Indexing
Section 5, Lecture 18
Hi Everyone,

Just a quick note on the upcoming lecture I create a numpy array that goes from 0 to 10, and I accidentally use the word "index" when I should have said "position".

I misspoke at two timestamps in the video- at 2:51 I say "5" is at index 6, while it's actually at index 5. What I meant to say is it is the 6th element in the array, but it is located at index 5 (just like a normal Python list, indexing starts at zero in Numpy arrays). Therefore, the arr[5:] notation actually grabs everything starting with the index 5, not everything beyond index 5. I then repeat the same thing at 3:21 by saying index 5 is at 4, what I should have said was the element 4 is the 5th element in the array, but it is still at index 4. 

Sorry for any confusion on this! Feel free to post to the QA forums if you get stuck on something, but for most people you should be able to watch the video lecture and clearly see how to index and slice arrays, it works exactly like a normal Python list.
********************************************************************************************************************************

In [51]:
import numpy as np

In [53]:
arr = np.arange(0,11)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
# to pick out one or some of the elements of an array, similar to indexing from python list

# basically, you use brackets and slice notation in order to do this

# type in the variable name of the array itself, pass in square brackets and then to get a single value
#     at an index, pass in a number

In [56]:
arr[8]

8

In [57]:
arr[1:5]  # starts at index 1, and stops at index 5, which is 4 (indexing starts at 0)

array([1, 2, 3, 4])

In [58]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [59]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [60]:
arr[5: ]   # slicing notation with a colon, starts at position 5 and grabs everything AFTER (not including) that position


array([ 5,  6,  7,  8,  9, 10])

In [62]:
arr[0:5] = 100

In [63]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
arr = np.arange(0,11)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
# slices of array

In [67]:
slice_of_arr = arr[0:6]

In [68]:
slice_of_arr  # shows the slice of the array from position 0 to 6

array([0, 1, 2, 3, 4, 5])

In [69]:
# broadcast on the array, meaning you say slice of array, use a colon to grab everything in slice

In [70]:
slice_of_arr[:] = 99

In [71]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [72]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
# copy method

arr_copy = arr.copy()

In [74]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
arr_copy[:] = 100

In [76]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [77]:
arr      # the original array is still unaffected by broadcast

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

***
If you grab a slice of array and set as variable, w/o saying you want a copy of array, the changes you make to the array will affect the original array.  

In [78]:
# indexing 

In [79]:
import numpy as np

In [80]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [81]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

two general formats for grabbing elements from a 2D array or Matrix

Double bracket format [[]]

and

Single bracket format with the comma

In [82]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [83]:
# if we want to grab the diget 5

In [84]:
arr_2d[0][0]

5

In [85]:
arr_2d[0]   # this will index the entire row back

array([ 5, 10, 15])

In [86]:
arr_2d[1][1]

25

In [87]:
arr_2d[0][1]

10

In [88]:
arr_2d[2][2]

45

In [90]:
arr_2d[2][0]

35

In [91]:
arr_2d[2][1]

40

In [92]:
# Single bracket notation with comma, best method, less prone to error

In [93]:
arr_2d[1,2]   # same as arr_2d[1][2]

30

In [96]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [94]:
# if you want sub-matrices from this matrix
# slice notation is used 

In [95]:
arr_2d[:2,1:]

# this slice grabs everything(rows 0 and 1) but not including row 2
#   and grabs everything from column 1 until the last column, but does not include column 1

array([[10, 15],
       [25, 30]])

In [97]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [98]:
arr_2d[:1, 0:]

array([[ 5, 10, 15]])

In [108]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [99]:
arr_2d[:1, 1:]

array([[10, 15]])

In [100]:
arr_2d[:2, 0:]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [104]:
arr_2d[:1,:1]

array([[5]])

In [107]:
arr_2d[:, :1]   # grabs only first column

array([[ 5],
       [20],
       [35]])

In [111]:
arr_2d[:, 1].reshape(3,1)   # grabs only second column ** had to reshape, bc it gave a 1x3 matrix

array([[10],
       [25],
       [40]])

In [112]:
# grab only second row [20,25,30]
arr_2d[1,:]

array([20, 25, 30])

In [113]:
# grab only third row [35,40,45]

arr_2d[2, :]

array([35, 40, 45])

In [114]:
# Conditional selection


In [115]:
arr = np.arange(1,11)

In [116]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
arr > 5  # gives an array of boolean values

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [118]:
bool_arr = arr > 5

In [119]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [120]:
# comparisson operator to index or conditionally select elements

# this will report parts of the array that return True

arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [121]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [122]:
# if we wanted to know all the elements of the array that are less than 3

arr[arr<3]  # returns all the elements where this condition is true

array([1, 2])

In [123]:
# exercise for this lecture
# first create a new 2d array, then try grabbing chunks of it with bracket notation and slicing

In [124]:
arr_2d = np.arange(50) .reshape(5,10)

In [125]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [126]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [127]:
# try grabbing  [26,27,28]
#               [36,37,38]

In [128]:
arr_2d[2:4,6:9]

array([[26, 27, 28],
       [36, 37, 38]])